---
title: "TFFF Staff Calendar"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      include = T,
                      message = F,
                      warning = F)

library(tidyverse)
library(leaflet)
library(googlesheets)
library(readxl)
library(janitor)
library(naniar)
library(crosstalk)
library(DT)
library(lubridate)
library(glue)
library(ggmap)


```

```{r themes}

tfff.dark.green <- "#265142"
tfff.light.green <- "#B5CC8E"
tfff.orange <- "#e65100"
tfff.yellow <- "#FBC02D"
tfff.blue <- "#283593"
tfff.red <- "#B71C1C"
tfff.brown <- "#51261C"
tfff.dark.gray <- "#545454"
tfff.medium.gray <- "#a8a8a8"
tfff.light.gray <- "#eeeeee"

```

```{r}
data <- read_excel("data/Program Staff Calendar Summary.xlsx", 
                   na = "TBD",
                   skip = 3) %>% 
  clean_names() %>% 
  separate_rows(city, sep = "/") %>% 
  separate_rows(city, sep = " or ") %>% 
  mutate(city = str_replace(city, "Central Oregon", "Bend")) %>% 
  rename("staff_person" = "staff") %>% 
  filter(!is.na(end_date)) %>% 
  filter(!is.na(city)) %>% 
  mutate(full_address = paste(city, state)) %>% 
  mutate_geocode(full_address) %>% 
  mutate(latitude = jitter(lat, amount = .01)) %>% 
  mutate(longitude = jitter(lon, amount = .01)) %>% 
  mutate(start_month = month(start_date)) %>% 
  mutate(end_month = month(end_date)) %>% 
  mutate(start_date_formatted = as.Date(start_date)) %>% 
  mutate(description = ifelse(is.na(description),
                              "No description",
                              description)) %>% 
  mutate(popup = paste("<strong>",
                       staff_person,
                       "</strong>",
                       "<br>",
                       description,
                       "<br>",
                       month.abb[start_month],
                       " ",
                       day(start_date),
                       " - ",
                       month.abb[end_month],
                       " ",
                       day(end_date),
                       "<br>",
                       city,
                       ", ",
                       state,
                       sep = "")) %>% 
  select(-c(lon, lat))
  

```




Map
=======================================================================
```{r crosstalk}

dk_sd <- SharedData$new(data)


```

Inputs {.sidebar}
-------------------------------------

### Notes

Please note that darker points on the map indicate multiple trips. Zoom in to see them. 

When you zoom in, please note that the dots are placed in approximate locations within municipalities. 

You can also zoom out to see trips taken throughout the United States.

Click on any point to learn more details about that trip.

### Filter by Date

Drag the filter below to see only trips taken during a particular time period.

```{r}
filter_slider("Date", 
              "", 
              dk_sd, 
              ~start_date_formatted, 
              dragRange = T,
              timeFormat = "%b %y",
              ticks = F)
```

Column
-------------------------------------
### 

```{r}
leaflet(dk_sd) %>%
  setView(-120.636236, 43.929386, 7) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(fillColor = tfff.light.green,
                   color = tfff.dark.green,
                   fillOpacity = .9,
                   popup = data$popup)


```

```{r}
data %>% 
  arrange(end_date) %>% 
  select(start_date:full_address) %>% 
  select(-city, -state) %>% 
  mutate(start_date_pretty = str_glue("{month.name[month(start_date)]} {day(start_date)}, {year(start_date)}")) %>% 
  mutate(end_date_pretty = str_glue("{month.name[month(end_date)]} {day(end_date)}, {year(end_date)}")) %>% 
  select(start_date_pretty, end_date_pretty, staff_person, full_address) %>% 
  datatable(colnames = c("Start Date",
                         "End Date",
                         "People",
                         "Destination"),
            rownames = F)

```



Table
=======================================================================

```{r}


data %>% 
  arrange(rev(end_date)) %>% 
  select(start_date:full_address) %>% 
  select(-city, -state) %>% 
  mutate(start_date_pretty = str_glue("{month.name[month(start_date)]} {day(start_date)}, {year(start_date)}")) %>% 
  mutate(end_date_pretty = str_glue("{month.name[month(end_date)]} {day(end_date)}, {year(end_date)}")) %>% 
  select(start_date_pretty, end_date_pretty, staff_person, full_address) %>% 
  datatable(colnames = c("Start Date",
                         "End Date",
                         "People",
                         "Destination"),
            rownames = F,
            options = list(
              pageLength = 10))

```


